export const mockJobProfile = {
  id: "emp-001",
  fullName: "Nguyễn Văn A",
  departmentName: "Phòng Kỹ thuật",
  positionName: "Kỹ sư phần mềm",
  joinDate: "2020-05-15",

  // 🧭 Lịch sử làm việc
  jobHistories: [
    {
      id: "j1",
      departmentName: "Phòng Kỹ thuật",
      positionName: "Kỹ sư phần mềm",
      contractType: "Hợp đồng chính thức",
      startDate: "2022-06-01",
      endDate: null, // hiện tại
      employmentStatus: "Đang làm việc",
      note: "Tham gia dự án quản lý nhân sự nội bộ",
    },
    {
      id: "j2",
      departmentName: "Phòng Kỹ thuật",
      positionName: "Thực tập sinh",
      contractType: "Thử việc 3 tháng",
      startDate: "2022-03-01",
      endDate: "2022-05-30",
      employmentStatus: "Đã kết thúc",
      note: "Hoàn thành chương trình thực tập xuất sắc",
    },
    {
      id: "j3",
      departmentName: "Phòng Hỗ trợ kỹ thuật",
      positionName: "Nhân viên hỗ trợ",
      contractType: "Hợp đồng thời vụ",
      startDate: "2021-01-01",
      endDate: "2021-12-31",
      employmentStatus: "Đã kết thúc",
      note: "Phụ trách xử lý sự cố khách hàng tại khu vực phía Nam",
    },
  ],

  // 🧩 Danh sách năng lực và chứng chỉ
  competencies: [
    {
      id: "c1",
      type: "Kỹ năng chuyên môn",
      name: "Java Spring Boot",
      level: "Advanced",
      issuedBy: "Tự học / Dự án nội bộ",
      issuedDate: "2021-09-15",
      expireDate: null,
      note: "Thành thạo REST API, JPA, Security, JWT",
    },
    {
      id: "c2",
      type: "Kỹ năng chuyên môn",
      name: "ReactJS",
      level: "Intermediate",
      issuedBy: "Udemy Certificate",
      issuedDate: "2022-04-10",
      expireDate: null,
      note: "Xây dựng component, hooks, redux, axios",
    },
    {
      id: "c3",
      type: "Kỹ năng mềm",
      name: "Giao tiếp và làm việc nhóm",
      level: "Advanced",
      issuedBy: "Phòng nhân sự",
      issuedDate: "2021-12-01",
      expireDate: null,
      note: "Hoạt động nhóm tốt, mentor cho 2 nhân viên mới",
    },
    {
      id: "c4",
      type: "Chứng chỉ nghề nghiệp",
      name: "AWS Certified Cloud Practitioner",
      level: "Basic",
      issuedBy: "Amazon Web Services",
      issuedDate: "2023-03-20",
      expireDate: "2026-03-20",
      note: "Kiến thức cơ bản về dịch vụ AWS, cloud deployment",
    },
    {
      id: "c5",
      type: "Kỹ năng chuyên môn",
      name: "SQL & Database Design",
      level: "Expert",
      issuedBy: "Coursera",
      issuedDate: "2020-08-05",
      expireDate: null,
      note: "Thiết kế, tối ưu hóa cơ sở dữ liệu, query nâng cao",
    },
    {
      id: "c6",
      type: "Chứng chỉ nội bộ",
      name: "Internal Security Awareness",
      level: "Beginner",
      issuedBy: "Phòng CNTT",
      issuedDate: "2024-02-01",
      expireDate: "2025-02-01",
      note: "Tuân thủ chính sách bảo mật và bảo vệ dữ liệu nội bộ",
    },
  ],
};
